### ISSUE TITLE
VRAM not detected properly

### ISSUE THREAD

**Issue by j-boers-13** [yamashi/PerformanceOverhaulCyberpunk#39] opened 2020-12-14 19:20 UTC
```
[2020-12-14 13:25:38.250] [info] Computed .text crc: D7E90F30
[2020-12-14 13:25:38.250] [info] 	Resolved to version: 1.04
[2020-12-14 13:25:38.283] [info] 	AMD SMT Patch: success
[2020-12-14 13:25:38.353] [info] 	Spectre patch: success
[2020-12-14 13:25:38.356] [info] 	Pool patch: success
[2020-12-14 13:25:38.358] [info] 	Virtual Input Patch: success
[2020-12-14 13:25:38.892] [info] 		Detected RAM: 15GB, using 11GB
[2020-12-14 13:25:38.892] [info] 		Using 4GB of VRAM
[2020-12-14 16:00:17.833] [info] Computed .text crc: D7E90F30
[2020-12-14 16:00:17.833] [info] 	Resolved to version: 1.04
[2020-12-14 16:00:17.866] [info] 	AMD SMT Patch: success
[2020-12-14 16:00:17.933] [info] 	Spectre patch: success
[2020-12-14 16:00:17.935] [info] 	Pool patch: success
[2020-12-14 16:00:17.937] [info] 	Virtual Input Patch: success
[2020-12-14 16:00:18.467] [info] 		Detected RAM: 15GB, using 11GB
[2020-12-14 16:00:18.467] [info] 		Using 4GB of VRAM
```

Hi, thanks for the great software, the patch worked well for me, but i noticed an issue with the VRAM detection.
The log file shows using 4GB of VRAM, but i have an rtx 2070 Super, which has 8GB VRAM, any tips on how to fix that?

Kind regards

**Comment by nwhiteman42** [comment] 2020-12-14 20:03
My VRAM allocation is inconsistent.

`[2020-12-14 08:15:43.030] [info] Computed .text crc: D7E90F30
[2020-12-14 08:15:43.030] [info] 	Resolved to version: 1.04
[2020-12-14 08:15:43.098] [info] 	Spectre patch: success
[2020-12-14 08:15:43.100] [info] 	Pool patch: success
[2020-12-14 08:15:43.102] [info] 	Virtual Input Patch: success
[2020-12-14 08:15:43.447] [info] 		Detected RAM: 31GB, using 27GB
[2020-12-14 08:15:43.548] [info] 		Using 8GB of VRAM
[2020-12-14 09:14:07.066] [info] Computed .text crc: D7E90F30
[2020-12-14 09:14:07.067] [info] 	Resolved to version: 1.04
[2020-12-14 09:14:07.148] [info] 	Spectre patch: success
[2020-12-14 09:14:07.149] [info] 	Pool patch: success
[2020-12-14 09:14:07.152] [info] 	Virtual Input Patch: success
[2020-12-14 09:14:07.564] [info] 		Detected RAM: 31GB, using 27GB
[2020-12-14 09:14:07.680] [info] 		Using 7GB of VRAM`

**Comment by clementinise** [comment] 2020-12-14 20:06
Please check the "Closed Issues" next time
#21

**Comment by clementinise** [comment] 2020-12-14 20:07
Duplicate of #21

**Closed** 2020-12-14 20:32 UTC
