### ISSUE TITLE
A new functionality has been added on Reddit "PoolCPU and PoolGPU Edit"

### ISSUE THREAD

**Issue by hadewych** [yamashi/PerformanceOverhaulCyberpunk#8] opened 2020-12-14 06:12 UTC
https://www.reddit.com/r/cyberpunkgame/comments/kccabx/hey_cd_projekt_red_i_think_you_shipped_the_wrong/

PoolCPU and PoolGPU

**Comment by yamashi** [comment] 2020-12-14 06:29
Duplicate of #3

**Closed by yamashi** 2020-12-14 06:29 UTC
